export const copy = {
  title: 'Datos',
  description: 'Los números del servidor, no los de un libro. Solo los ve quien administra.',
  usuarios: 'Cuentas',
  usuariosHint: 'Gente con cuenta en esta instancia, esté en el libro que esté.',
  loading: 'Cargando los datos',

  acceso: {
    title: 'Dar acceso',
    hint: 'Para quien te pidió entrar. Se registra con su propia contraseña y arranca con su libro Personal, sin ver el tuyo.',
    email: 'Su correo',
    placeholder: 'nombre@correo.com',
    submit: 'Crear la invitación',
    submitting: 'Creando',
    linkLabel: 'El enlace para esa persona',
    linkHint: (fecha: string) => `Sirve una sola vez y vence el ${fecha}. Todavía no mandamos correos: pasáselo vos.`,
    copy: 'Copiar el enlace',
    copied: 'Enlace copiado.',
    copyFailed: 'No se pudo copiar. Seleccioná el enlace y copialo a mano.',
    pending: 'Esperando que se registren',
    none: 'No hay invitaciones esperando.',
    expires: (fecha: string) => `vence el ${fecha}`,
    copyShort: 'Copiar',
    cancel: 'Cancelar',
    cancelled: 'Invitación cancelada.',
    alreadyHasAccount: 'Ese correo ya tiene cuenta.',
    failed: 'No se pudo crear la invitación.',
  },
} as const
