import type { AccountProps } from '../domain/account.js'

// La semilla corre una sola vez, al arrancar con la tabla vacía. No es una migración de
// datos que se reaplique: si Emilio borra una cuenta semilla, es porque no la quiere, y
// volver a meterla en el siguiente arranque sería el sistema discutiendo con su usuario.
export const CHART_SEED: readonly AccountProps[] = [
  {
    code: '1000',
    name: 'Activos',
    accountClass: 'ASSET',
    parentCode: null,
    active: true,
    sortOrder: 10,
  },
  {
    code: '1100',
    name: 'Efectivo y equivalentes',
    accountClass: 'ASSET',
    parentCode: '1000',
    active: true,
    sortOrder: 10,
  },
  {
    code: '1101',
    name: 'Caja colones',
    accountClass: 'ASSET',
    parentCode: '1100',
    active: true,
    sortOrder: 10,
  },
  {
    code: '1102',
    name: 'Caja dólares',
    accountClass: 'ASSET',
    parentCode: '1100',
    active: true,
    sortOrder: 20,
  },
  {
    code: '1111',
    name: 'Banco colones',
    accountClass: 'ASSET',
    parentCode: '1100',
    active: true,
    sortOrder: 30,
  },
  {
    code: '1112',
    name: 'Banco dólares',
    accountClass: 'ASSET',
    parentCode: '1100',
    active: true,
    sortOrder: 40,
  },
  // Su saldo en cada moneda queda distinto de cero solo mientras una conversión esté a
  // medio registrar. Si un día no está en cero, hay un asiento incompleto.
  {
    code: '1190',
    name: 'Traslados entre monedas',
    accountClass: 'ASSET',
    parentCode: '1100',
    active: true,
    isCurrencyBridge: true,
    sortOrder: 90,
  },
  {
    code: '1200',
    name: 'Cuentas por cobrar',
    accountClass: 'ASSET',
    parentCode: '1000',
    active: true,
    sortOrder: 20,
  },
  // Lo puesto a plazo no es efectivo: está comprometido hasta que vence. Separarlo evita
  // que el saldo de banco diga que hay plata disponible que no lo está.
  {
    code: '1300',
    name: 'Inversiones',
    accountClass: 'ASSET',
    parentCode: '1000',
    active: true,
    sortOrder: 30,
  },
  {
    code: '2000',
    name: 'Pasivos',
    accountClass: 'LIABILITY',
    parentCode: null,
    active: true,
    sortOrder: 20,
  },
  {
    code: '2100',
    name: 'Cuentas por pagar',
    accountClass: 'LIABILITY',
    parentCode: '2000',
    active: true,
    sortOrder: 10,
  },
  {
    code: '3000',
    name: 'Patrimonio',
    accountClass: 'EQUITY',
    parentCode: null,
    active: true,
    sortOrder: 30,
  },
  {
    code: '3110',
    name: 'Aportes',
    accountClass: 'EQUITY',
    parentCode: '3000',
    active: true,
    sortOrder: 10,
  },
  {
    code: '3210',
    name: 'Resultados acumulados',
    accountClass: 'EQUITY',
    parentCode: '3000',
    active: true,
    sortOrder: 20,
  },
  {
    code: '4000',
    name: 'Ingresos',
    accountClass: 'INCOME',
    parentCode: null,
    active: true,
    sortOrder: 40,
  },
  {
    code: '4100',
    name: 'Ingresos',
    accountClass: 'INCOME',
    parentCode: '4000',
    active: true,
    sortOrder: 10,
  },
  {
    code: '5000',
    name: 'Costo de ingresos',
    accountClass: 'COST_OF_REVENUE',
    parentCode: null,
    active: true,
    sortOrder: 50,
  },
  {
    code: '6000',
    name: 'Gastos operativos',
    accountClass: 'OPERATING_EXPENSE',
    parentCode: null,
    active: true,
    sortOrder: 60,
  },
  {
    code: '6100',
    name: 'Gastos generales',
    accountClass: 'OPERATING_EXPENSE',
    parentCode: '6000',
    active: true,
    sortOrder: 10,
  },
]
