/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CrearCuentaRouteImport } from './routes/crear-cuenta'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as DeudasRouteImport } from './routes/deudas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as LibroRouteImport } from './routes/libro'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as PlanDePagoRouteImport } from './routes/plan-de-pago'
import { Route as ProyeccionRouteImport } from './routes/proyeccion'
import { Route as TableroRouteImport } from './routes/tablero'
import { Route as UnirseRouteImport } from './routes/unirse'
import { Route as BancoConciliacionRouteImport } from './routes/banco.conciliacion'
import { Route as BancoCuentasRouteImport } from './routes/banco.cuentas'
import { Route as BancoImportarRouteImport } from './routes/banco.importar'
import { Route as ContabilidadAsientosRouteImport } from './routes/contabilidad.asientos'
import { Route as ContabilidadCategoriasRouteImport } from './routes/contabilidad.categorias'
import { Route as ContabilidadCierreRouteImport } from './routes/contabilidad.cierre'
import { Route as ContabilidadComprobacionRouteImport } from './routes/contabilidad.comprobacion'
import { Route as ContabilidadCuentasRouteImport } from './routes/contabilidad.cuentas'
import { Route as ContabilidadMayorRouteImport } from './routes/contabilidad.mayor'
import { Route as ContabilidadMovimientosRouteImport } from './routes/contabilidad.movimientos'
import { Route as ContabilidadPatrimonioRouteImport } from './routes/contabilidad.patrimonio'
import { Route as ContabilidadResultadosRouteImport } from './routes/contabilidad.resultados'
import { Route as ContabilidadSituacionRouteImport } from './routes/contabilidad.situacion'
import { Route as DeudasIndexRouteImport } from './routes/deudas.index'
import { Route as InversionesIndexRouteImport } from './routes/inversiones.index'
import { Route as InversionesInvestmentIdRouteImport } from './routes/inversiones.$investmentId'
import { Route as MetasIndexRouteImport } from './routes/metas.index'
import { Route as MetasGoalIdRouteImport } from './routes/metas.$goalId'
import { Route as PresupuestoIndexRouteImport } from './routes/presupuesto.index'
import { Route as PresupuestoModelosRouteImport } from './routes/presupuesto.modelos'
import { Route as DeudasDebtIdIndexRouteImport } from './routes/deudas.$debtId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaRoute = CrearCuentaRouteImport.update({
  id: '/crear-cuenta',
  path: '/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasRoute = DeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroRoute = LibroRouteImport.update({
  id: '/libro',
  path: '/libro',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDePagoRoute = PlanDePagoRouteImport.update({
  id: '/plan-de-pago',
  path: '/plan-de-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyeccionRoute = ProyeccionRouteImport.update({
  id: '/proyeccion',
  path: '/proyeccion',
  getParentRoute: () => rootRouteImport,
} as any)
const TableroRoute = TableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseRoute = UnirseRouteImport.update({
  id: '/unirse',
  path: '/unirse',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoConciliacionRoute = BancoConciliacionRouteImport.update({
  id: '/banco/conciliacion',
  path: '/banco/conciliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoCuentasRoute = BancoCuentasRouteImport.update({
  id: '/banco/cuentas',
  path: '/banco/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoImportarRoute = BancoImportarRouteImport.update({
  id: '/banco/importar',
  path: '/banco/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadAsientosRoute = ContabilidadAsientosRouteImport.update({
  id: '/contabilidad/asientos',
  path: '/contabilidad/asientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadCategoriasRoute = ContabilidadCategoriasRouteImport.update({
  id: '/contabilidad/categorias',
  path: '/contabilidad/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadCierreRoute = ContabilidadCierreRouteImport.update({
  id: '/contabilidad/cierre',
  path: '/contabilidad/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadComprobacionRoute =
  ContabilidadComprobacionRouteImport.update({
    id: '/contabilidad/comprobacion',
    path: '/contabilidad/comprobacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContabilidadCuentasRoute = ContabilidadCuentasRouteImport.update({
  id: '/contabilidad/cuentas',
  path: '/contabilidad/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadMayorRoute = ContabilidadMayorRouteImport.update({
  id: '/contabilidad/mayor',
  path: '/contabilidad/mayor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadMovimientosRoute = ContabilidadMovimientosRouteImport.update({
  id: '/contabilidad/movimientos',
  path: '/contabilidad/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadPatrimonioRoute = ContabilidadPatrimonioRouteImport.update({
  id: '/contabilidad/patrimonio',
  path: '/contabilidad/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadResultadosRoute = ContabilidadResultadosRouteImport.update({
  id: '/contabilidad/resultados',
  path: '/contabilidad/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadSituacionRoute = ContabilidadSituacionRouteImport.update({
  id: '/contabilidad/situacion',
  path: '/contabilidad/situacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasIndexRoute = DeudasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeudasRoute,
} as any)
const InversionesIndexRoute = InversionesIndexRouteImport.update({
  id: '/inversiones/',
  path: '/inversiones/',
  getParentRoute: () => rootRouteImport,
} as any)
const InversionesInvestmentIdRoute = InversionesInvestmentIdRouteImport.update({
  id: '/inversiones/$investmentId',
  path: '/inversiones/$investmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasIndexRoute = MetasIndexRouteImport.update({
  id: '/metas/',
  path: '/metas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasGoalIdRoute = MetasGoalIdRouteImport.update({
  id: '/metas/$goalId',
  path: '/metas/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoIndexRoute = PresupuestoIndexRouteImport.update({
  id: '/presupuesto/',
  path: '/presupuesto/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoModelosRoute = PresupuestoModelosRouteImport.update({
  id: '/presupuesto/modelos',
  path: '/presupuesto/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasDebtIdIndexRoute = DeudasDebtIdIndexRouteImport.update({
  id: '/$debtId/',
  path: '/$debtId/',
  getParentRoute: () => DeudasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/cuenta': typeof CuentaRoute
  '/deudas': typeof DeudasRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/guia': typeof GuiaRoute
  '/libro': typeof LibroRoute
  '/novedades': typeof NovedadesRoute
  '/plan-de-pago': typeof PlanDePagoRoute
  '/proyeccion': typeof ProyeccionRoute
  '/tablero': typeof TableroRoute
  '/unirse': typeof UnirseRoute
  '/banco/conciliacion': typeof BancoConciliacionRoute
  '/banco/cuentas': typeof BancoCuentasRoute
  '/banco/importar': typeof BancoImportarRoute
  '/contabilidad/asientos': typeof ContabilidadAsientosRoute
  '/contabilidad/categorias': typeof ContabilidadCategoriasRoute
  '/contabilidad/cierre': typeof ContabilidadCierreRoute
  '/contabilidad/comprobacion': typeof ContabilidadComprobacionRoute
  '/contabilidad/cuentas': typeof ContabilidadCuentasRoute
  '/contabilidad/mayor': typeof ContabilidadMayorRoute
  '/contabilidad/movimientos': typeof ContabilidadMovimientosRoute
  '/contabilidad/patrimonio': typeof ContabilidadPatrimonioRoute
  '/contabilidad/resultados': typeof ContabilidadResultadosRoute
  '/contabilidad/situacion': typeof ContabilidadSituacionRoute
  '/inversiones/$investmentId': typeof InversionesInvestmentIdRoute
  '/metas/$goalId': typeof MetasGoalIdRoute
  '/presupuesto/modelos': typeof PresupuestoModelosRoute
  '/deudas/': typeof DeudasIndexRoute
  '/inversiones/': typeof InversionesIndexRoute
  '/metas/': typeof MetasIndexRoute
  '/presupuesto/': typeof PresupuestoIndexRoute
  '/deudas/$debtId/': typeof DeudasDebtIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/cuenta': typeof CuentaRoute
  '/entrar': typeof EntrarRoute
  '/guia': typeof GuiaRoute
  '/libro': typeof LibroRoute
  '/novedades': typeof NovedadesRoute
  '/plan-de-pago': typeof PlanDePagoRoute
  '/proyeccion': typeof ProyeccionRoute
  '/tablero': typeof TableroRoute
  '/unirse': typeof UnirseRoute
  '/banco/conciliacion': typeof BancoConciliacionRoute
  '/banco/cuentas': typeof BancoCuentasRoute
  '/banco/importar': typeof BancoImportarRoute
  '/contabilidad/asientos': typeof ContabilidadAsientosRoute
  '/contabilidad/categorias': typeof ContabilidadCategoriasRoute
  '/contabilidad/cierre': typeof ContabilidadCierreRoute
  '/contabilidad/comprobacion': typeof ContabilidadComprobacionRoute
  '/contabilidad/cuentas': typeof ContabilidadCuentasRoute
  '/contabilidad/mayor': typeof ContabilidadMayorRoute
  '/contabilidad/movimientos': typeof ContabilidadMovimientosRoute
  '/contabilidad/patrimonio': typeof ContabilidadPatrimonioRoute
  '/contabilidad/resultados': typeof ContabilidadResultadosRoute
  '/contabilidad/situacion': typeof ContabilidadSituacionRoute
  '/inversiones/$investmentId': typeof InversionesInvestmentIdRoute
  '/metas/$goalId': typeof MetasGoalIdRoute
  '/presupuesto/modelos': typeof PresupuestoModelosRoute
  '/deudas': typeof DeudasIndexRoute
  '/inversiones': typeof InversionesIndexRoute
  '/metas': typeof MetasIndexRoute
  '/presupuesto': typeof PresupuestoIndexRoute
  '/deudas/$debtId': typeof DeudasDebtIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/cuenta': typeof CuentaRoute
  '/deudas': typeof DeudasRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/guia': typeof GuiaRoute
  '/libro': typeof LibroRoute
  '/novedades': typeof NovedadesRoute
  '/plan-de-pago': typeof PlanDePagoRoute
  '/proyeccion': typeof ProyeccionRoute
  '/tablero': typeof TableroRoute
  '/unirse': typeof UnirseRoute
  '/banco/conciliacion': typeof BancoConciliacionRoute
  '/banco/cuentas': typeof BancoCuentasRoute
  '/banco/importar': typeof BancoImportarRoute
  '/contabilidad/asientos': typeof ContabilidadAsientosRoute
  '/contabilidad/categorias': typeof ContabilidadCategoriasRoute
  '/contabilidad/cierre': typeof ContabilidadCierreRoute
  '/contabilidad/comprobacion': typeof ContabilidadComprobacionRoute
  '/contabilidad/cuentas': typeof ContabilidadCuentasRoute
  '/contabilidad/mayor': typeof ContabilidadMayorRoute
  '/contabilidad/movimientos': typeof ContabilidadMovimientosRoute
  '/contabilidad/patrimonio': typeof ContabilidadPatrimonioRoute
  '/contabilidad/resultados': typeof ContabilidadResultadosRoute
  '/contabilidad/situacion': typeof ContabilidadSituacionRoute
  '/inversiones/$investmentId': typeof InversionesInvestmentIdRoute
  '/metas/$goalId': typeof MetasGoalIdRoute
  '/presupuesto/modelos': typeof PresupuestoModelosRoute
  '/deudas/': typeof DeudasIndexRoute
  '/inversiones/': typeof InversionesIndexRoute
  '/metas/': typeof MetasIndexRoute
  '/presupuesto/': typeof PresupuestoIndexRoute
  '/deudas/$debtId/': typeof DeudasDebtIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/crear-cuenta'
    | '/cuenta'
    | '/deudas'
    | '/entrar'
    | '/guia'
    | '/libro'
    | '/novedades'
    | '/plan-de-pago'
    | '/proyeccion'
    | '/tablero'
    | '/unirse'
    | '/banco/conciliacion'
    | '/banco/cuentas'
    | '/banco/importar'
    | '/contabilidad/asientos'
    | '/contabilidad/categorias'
    | '/contabilidad/cierre'
    | '/contabilidad/comprobacion'
    | '/contabilidad/cuentas'
    | '/contabilidad/mayor'
    | '/contabilidad/movimientos'
    | '/contabilidad/patrimonio'
    | '/contabilidad/resultados'
    | '/contabilidad/situacion'
    | '/inversiones/$investmentId'
    | '/metas/$goalId'
    | '/presupuesto/modelos'
    | '/deudas/'
    | '/inversiones/'
    | '/metas/'
    | '/presupuesto/'
    | '/deudas/$debtId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/crear-cuenta'
    | '/cuenta'
    | '/entrar'
    | '/guia'
    | '/libro'
    | '/novedades'
    | '/plan-de-pago'
    | '/proyeccion'
    | '/tablero'
    | '/unirse'
    | '/banco/conciliacion'
    | '/banco/cuentas'
    | '/banco/importar'
    | '/contabilidad/asientos'
    | '/contabilidad/categorias'
    | '/contabilidad/cierre'
    | '/contabilidad/comprobacion'
    | '/contabilidad/cuentas'
    | '/contabilidad/mayor'
    | '/contabilidad/movimientos'
    | '/contabilidad/patrimonio'
    | '/contabilidad/resultados'
    | '/contabilidad/situacion'
    | '/inversiones/$investmentId'
    | '/metas/$goalId'
    | '/presupuesto/modelos'
    | '/deudas'
    | '/inversiones'
    | '/metas'
    | '/presupuesto'
    | '/deudas/$debtId'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/crear-cuenta'
    | '/cuenta'
    | '/deudas'
    | '/entrar'
    | '/guia'
    | '/libro'
    | '/novedades'
    | '/plan-de-pago'
    | '/proyeccion'
    | '/tablero'
    | '/unirse'
    | '/banco/conciliacion'
    | '/banco/cuentas'
    | '/banco/importar'
    | '/contabilidad/asientos'
    | '/contabilidad/categorias'
    | '/contabilidad/cierre'
    | '/contabilidad/comprobacion'
    | '/contabilidad/cuentas'
    | '/contabilidad/mayor'
    | '/contabilidad/movimientos'
    | '/contabilidad/patrimonio'
    | '/contabilidad/resultados'
    | '/contabilidad/situacion'
    | '/inversiones/$investmentId'
    | '/metas/$goalId'
    | '/presupuesto/modelos'
    | '/deudas/'
    | '/inversiones/'
    | '/metas/'
    | '/presupuesto/'
    | '/deudas/$debtId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CrearCuentaRoute: typeof CrearCuentaRoute
  CuentaRoute: typeof CuentaRoute
  DeudasRoute: typeof DeudasRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  GuiaRoute: typeof GuiaRoute
  LibroRoute: typeof LibroRoute
  NovedadesRoute: typeof NovedadesRoute
  PlanDePagoRoute: typeof PlanDePagoRoute
  ProyeccionRoute: typeof ProyeccionRoute
  TableroRoute: typeof TableroRoute
  UnirseRoute: typeof UnirseRoute
  BancoConciliacionRoute: typeof BancoConciliacionRoute
  BancoCuentasRoute: typeof BancoCuentasRoute
  BancoImportarRoute: typeof BancoImportarRoute
  ContabilidadAsientosRoute: typeof ContabilidadAsientosRoute
  ContabilidadCategoriasRoute: typeof ContabilidadCategoriasRoute
  ContabilidadCierreRoute: typeof ContabilidadCierreRoute
  ContabilidadComprobacionRoute: typeof ContabilidadComprobacionRoute
  ContabilidadCuentasRoute: typeof ContabilidadCuentasRoute
  ContabilidadMayorRoute: typeof ContabilidadMayorRoute
  ContabilidadMovimientosRoute: typeof ContabilidadMovimientosRoute
  ContabilidadPatrimonioRoute: typeof ContabilidadPatrimonioRoute
  ContabilidadResultadosRoute: typeof ContabilidadResultadosRoute
  ContabilidadSituacionRoute: typeof ContabilidadSituacionRoute
  InversionesInvestmentIdRoute: typeof InversionesInvestmentIdRoute
  MetasGoalIdRoute: typeof MetasGoalIdRoute
  PresupuestoModelosRoute: typeof PresupuestoModelosRoute
  InversionesIndexRoute: typeof InversionesIndexRoute
  MetasIndexRoute: typeof MetasIndexRoute
  PresupuestoIndexRoute: typeof PresupuestoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta': {
      id: '/crear-cuenta'
      path: '/crear-cuenta'
      fullPath: '/crear-cuenta'
      preLoaderRoute: typeof CrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas': {
      id: '/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof DeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro': {
      id: '/libro'
      path: '/libro'
      fullPath: '/libro'
      preLoaderRoute: typeof LibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-de-pago': {
      id: '/plan-de-pago'
      path: '/plan-de-pago'
      fullPath: '/plan-de-pago'
      preLoaderRoute: typeof PlanDePagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyeccion': {
      id: '/proyeccion'
      path: '/proyeccion'
      fullPath: '/proyeccion'
      preLoaderRoute: typeof ProyeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablero': {
      id: '/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof TableroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse': {
      id: '/unirse'
      path: '/unirse'
      fullPath: '/unirse'
      preLoaderRoute: typeof UnirseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco/conciliacion': {
      id: '/banco/conciliacion'
      path: '/banco/conciliacion'
      fullPath: '/banco/conciliacion'
      preLoaderRoute: typeof BancoConciliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco/cuentas': {
      id: '/banco/cuentas'
      path: '/banco/cuentas'
      fullPath: '/banco/cuentas'
      preLoaderRoute: typeof BancoCuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco/importar': {
      id: '/banco/importar'
      path: '/banco/importar'
      fullPath: '/banco/importar'
      preLoaderRoute: typeof BancoImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/asientos': {
      id: '/contabilidad/asientos'
      path: '/contabilidad/asientos'
      fullPath: '/contabilidad/asientos'
      preLoaderRoute: typeof ContabilidadAsientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/categorias': {
      id: '/contabilidad/categorias'
      path: '/contabilidad/categorias'
      fullPath: '/contabilidad/categorias'
      preLoaderRoute: typeof ContabilidadCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/cierre': {
      id: '/contabilidad/cierre'
      path: '/contabilidad/cierre'
      fullPath: '/contabilidad/cierre'
      preLoaderRoute: typeof ContabilidadCierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/comprobacion': {
      id: '/contabilidad/comprobacion'
      path: '/contabilidad/comprobacion'
      fullPath: '/contabilidad/comprobacion'
      preLoaderRoute: typeof ContabilidadComprobacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/cuentas': {
      id: '/contabilidad/cuentas'
      path: '/contabilidad/cuentas'
      fullPath: '/contabilidad/cuentas'
      preLoaderRoute: typeof ContabilidadCuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/mayor': {
      id: '/contabilidad/mayor'
      path: '/contabilidad/mayor'
      fullPath: '/contabilidad/mayor'
      preLoaderRoute: typeof ContabilidadMayorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/movimientos': {
      id: '/contabilidad/movimientos'
      path: '/contabilidad/movimientos'
      fullPath: '/contabilidad/movimientos'
      preLoaderRoute: typeof ContabilidadMovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/patrimonio': {
      id: '/contabilidad/patrimonio'
      path: '/contabilidad/patrimonio'
      fullPath: '/contabilidad/patrimonio'
      preLoaderRoute: typeof ContabilidadPatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/resultados': {
      id: '/contabilidad/resultados'
      path: '/contabilidad/resultados'
      fullPath: '/contabilidad/resultados'
      preLoaderRoute: typeof ContabilidadResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad/situacion': {
      id: '/contabilidad/situacion'
      path: '/contabilidad/situacion'
      fullPath: '/contabilidad/situacion'
      preLoaderRoute: typeof ContabilidadSituacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas/': {
      id: '/deudas/'
      path: '/'
      fullPath: '/deudas/'
      preLoaderRoute: typeof DeudasIndexRouteImport
      parentRoute: typeof DeudasRoute
    }
    '/inversiones/': {
      id: '/inversiones/'
      path: '/inversiones'
      fullPath: '/inversiones/'
      preLoaderRoute: typeof InversionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversiones/$investmentId': {
      id: '/inversiones/$investmentId'
      path: '/inversiones/$investmentId'
      fullPath: '/inversiones/$investmentId'
      preLoaderRoute: typeof InversionesInvestmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas/': {
      id: '/metas/'
      path: '/metas'
      fullPath: '/metas/'
      preLoaderRoute: typeof MetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas/$goalId': {
      id: '/metas/$goalId'
      path: '/metas/$goalId'
      fullPath: '/metas/$goalId'
      preLoaderRoute: typeof MetasGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto/': {
      id: '/presupuesto/'
      path: '/presupuesto'
      fullPath: '/presupuesto/'
      preLoaderRoute: typeof PresupuestoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto/modelos': {
      id: '/presupuesto/modelos'
      path: '/presupuesto/modelos'
      fullPath: '/presupuesto/modelos'
      preLoaderRoute: typeof PresupuestoModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas/$debtId/': {
      id: '/deudas/$debtId/'
      path: '/$debtId'
      fullPath: '/deudas/$debtId/'
      preLoaderRoute: typeof DeudasDebtIdIndexRouteImport
      parentRoute: typeof DeudasRoute
    }
  }
}

interface DeudasRouteChildren {
  DeudasIndexRoute: typeof DeudasIndexRoute
  DeudasDebtIdIndexRoute: typeof DeudasDebtIdIndexRoute
}

const DeudasRouteChildren: DeudasRouteChildren = {
  DeudasIndexRoute: DeudasIndexRoute,
  DeudasDebtIdIndexRoute: DeudasDebtIdIndexRoute,
}

const DeudasRouteWithChildren =
  DeudasRoute._addFileChildren(DeudasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CrearCuentaRoute: CrearCuentaRoute,
  CuentaRoute: CuentaRoute,
  DeudasRoute: DeudasRouteWithChildren,
  EntrarRoute: EntrarRoute,
  GuiaRoute: GuiaRoute,
  LibroRoute: LibroRoute,
  NovedadesRoute: NovedadesRoute,
  PlanDePagoRoute: PlanDePagoRoute,
  ProyeccionRoute: ProyeccionRoute,
  TableroRoute: TableroRoute,
  UnirseRoute: UnirseRoute,
  BancoConciliacionRoute: BancoConciliacionRoute,
  BancoCuentasRoute: BancoCuentasRoute,
  BancoImportarRoute: BancoImportarRoute,
  ContabilidadAsientosRoute: ContabilidadAsientosRoute,
  ContabilidadCategoriasRoute: ContabilidadCategoriasRoute,
  ContabilidadCierreRoute: ContabilidadCierreRoute,
  ContabilidadComprobacionRoute: ContabilidadComprobacionRoute,
  ContabilidadCuentasRoute: ContabilidadCuentasRoute,
  ContabilidadMayorRoute: ContabilidadMayorRoute,
  ContabilidadMovimientosRoute: ContabilidadMovimientosRoute,
  ContabilidadPatrimonioRoute: ContabilidadPatrimonioRoute,
  ContabilidadResultadosRoute: ContabilidadResultadosRoute,
  ContabilidadSituacionRoute: ContabilidadSituacionRoute,
  InversionesInvestmentIdRoute: InversionesInvestmentIdRoute,
  MetasGoalIdRoute: MetasGoalIdRoute,
  PresupuestoModelosRoute: PresupuestoModelosRoute,
  InversionesIndexRoute: InversionesIndexRoute,
  MetasIndexRoute: MetasIndexRoute,
  PresupuestoIndexRoute: PresupuestoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
